name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ "main" ]

jobs:
  ci-build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        
    - name: Check Dependencies and Environment
      run: uv sync
        
    - name: Lint Code with Ruff
      run: |
        uv pip install ruff
        uv run ruff check .
        
    - name: Run Smoke Test
      run: uv run python -c "import torch; import lightning; print('Modules successfully imported!')"

  cd-build-and-deploy:
    needs: ci-build-and-test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv and build tools
      uses: astral-sh/setup-uv@v3
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Build python package
      run: |
        uv pip install build
        uv run python -m build
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
